# Generated by Django 5.1.6 on 2025-07-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_texte', models.CharField(max_length=50)),
                ('titre', models.CharField(max_length=255)),
                ('secteur', models.CharField(max_length=100)),
                ('date_enregistrement', models.DateField()),
                ('type_document', models.CharField(choices=[('entrant', 'Entrant'), ('sortant', 'Sortant')], max_length=10)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
    ]
